{% set name = "pymt_frost_number" %}
{% set version = "0.1" %}
{% set build = "0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ..

build:
  number: {{ build }}
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - setuptools
    - numpy 1.11.*
    - cython
    - model_metadata
    - permamodel >0.1.3

  run:
    - python
    - setuptools
    - pymt
    - permamodel >0.1.3

test:
  requires:
    - bmi-tester
  imports:
    - pymt_frost_number
  commands:
    - bmi-test permamodel.components.bmi_frost_number:BmiFrostnumberMethod --infile=$(mmd-stage BmiFrostnumberMethod .)

about:
  summary: PyMT plugin for frost_number.
  home: https://github.com/mcflugen/pymt_frost_number
  license: MIT license
  license_file: LICENSE
  dev_url: https://github.com/mcflugen/pymt_frost_number
